# Generated by Django 5.0.4 on 2024-04-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_pic",
        ),
    ]
