# Generated by Django 5.0.4 on 2024-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_profile_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
