# Generated by Django 5.0.4 on 2024-04-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_authorprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorProfile",
        ),
    ]
