# Generated by Django 5.0.1 on 2024-04-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_comment_follower_like_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="post",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="user",
        ),
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="view",
            name="post",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="View",
        ),
    ]
