# Generated by Django 5.0.1 on 2024-04-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_postcomment_postlike_postview"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="postview",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="postview",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postview",
            name="user",
        ),
        migrations.DeleteModel(
            name="PostComment",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
        migrations.DeleteModel(
            name="PostView",
        ),
    ]
